apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: openflow-legacy
    port: 6633
  - name: openflow
    port: 6653
  - name: ovsdb
    port: 6640
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
