nameOverride: ""

image:
  repository: voltha-onos  #onosproject/onos #voltha-onos 
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

replicas: 3
heap: 4G
apps:
- org.onosproject.hostprovider
- org.onosproject.openflow
- org.onosproject.mcast

atomix:
  replicas: 3

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10

resources:
  requests:
    cpu: 0.5
    memory: 512Mi
