apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-probe-scripts
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  check-onos-status: |
    #!/bin/bash
    set -e
    host=$(hostname -s)
    config=$(curl -s http://$host:8181/onos/v1/cluster/$host --user onos:rocks)
    echo $config
    printf '%q' $config | grep -q "READY"