apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: tutum/dnsutils:latest
        env:
        - name: ATOMIX_SERVICE
          value: {{ template "atomix.fullname" . }}
        - name: ATOMIX_REPLICAS
          value: {{ .Values.atomix.replicas | quote }}
        command:
        - sh
        - -c
        - "/scripts/configure-onos.sh $ATOMIX_SERVICE $ATOMIX_REPLICAS > /config/cluster.json && touch /config/active"
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
        - name: config
          mountPath: /config
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #resources:
          #requests:
            #memory: {{ .Values.resources.requests.memory }}
            #cpu: {{ .Values.resources.requests.cpu }}
        env:
        - name: JAVA_OPTS
          value: -Xmx{{ default "2G" .Values.heap }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ONOS_APPS
          value: org.opencord.sadis
        ports:
        - name: openflow
          containerPort: 6653
        - name: ovsdb
          containerPort: 6640
        - name: east-west
          containerPort: 9876
        - name: cli
          containerPort: 8101
        - name: ui
          containerPort: 8181
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - /root/onos/bin/check-onos-status
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 10
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /root/onos/bin/check-onos-status
          initialDelaySeconds: 300
          periodSeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: probe-scripts
          mountPath: /root/onos/bin/check-onos-status
          subPath: check-onos-status
        - name: config
          mountPath: /root/onos/config/cluster.json
          subPath: cluster.json
        {{- range .Values.apps }}
        - name: config
          mountPath: /root/onos/apps/{{ . }}/active
          subPath: active
        {{- end }}
      volumes:
      - name: init-scripts
        configMap:
          name: {{ template "fullname" . }}-init-scripts
          defaultMode: 0744
      - name: probe-scripts
        configMap:
          name: {{ template "fullname" . }}-probe-scripts
          defaultMode: 0744
      - name: config
        emptyDir: {}
